### ISSUE TITLE
Citing?

### ISSUE THREAD

**Issue by endrebak** [phaverty/GenomicVectors.jl#13]
I'm writing up a paper on my pyranges package for BioRxiv and I'd like to cite GenomicVectors (showing that the genomicrange is a fundamental datastructure that exists in several languages). How do you prefer I cite GenomicVectors.jl? Do you have any intentions of throwing together a preprint or should I just link to the repo or what?

**Comment by endrebak** [comment]
I'll try

```
@misc{Haverty2017,
  author = {Haverty, Peter},
  title = {GenomicVectors.jl},
  year = {2017},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/phaverty/GenomicVectors.jl}},
}
```

**Comment by endrebak** [comment]
Possible, but a bit of work for you: https://guides.github.com/activities/citable-code/

**Comment by phaverty** [comment]
Thanks for contacting me. I'll look into the citable code option!

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com
