### ISSUE TITLE
Are you still working on this, Pete?

### ISSUE THREAD

**Issue by LTLA** [phaverty/GenomicVectors.jl#28]
I'm playing around with porting over some of the BioC data structures to Julia (see https://github.com/LTLA/SummarizedExperiments.jl) and I was thinking about what to do for `GRanges` and `GRangesList` classes to put in the `RangedSummarizedExperiment`. 

I've looked at `GenomicFeatures.jl` and it's probably serviceable but it's not a 100% drop-in replacement for the BioC equivalents. It seems that your class might be a bit more amenable, but I don't know if this is still something you're working on.

**Comment by phaverty** [comment]
Hey Aaron! Great to hear from you. I haven't worked on this for a bit, but it still works. Let me know if you have suggestions. I'd be happy to add features.
Right, this one is more like GRanges than the official BioJulia class.

**Comment by Zymergen-phaverty** [comment]
In particular, I'm not super excited about my vectorization implementation here and over in RleVectors.jl. Suggestions most welcome.

**Comment by LTLA** [comment]
Great. I'll need to play around with this package a bit further, but  my initial thought would be that I'd like to see a `GRangesList` equivalent. Not 100% sure how one would implement that here - I guess as a `Vector{GenomicRanges{T}}`, but somehow keeping the `GenomeInfo` the same across all entries.

In the meantime, I need to finish the Julia interface to a certain database that you were working on before you left...

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@LTLA , another user sent in a pull request so I got excited and updated the CI/CD stuff for this an RLEVectors.jl
Are you still Julia-ify-ing my favorite app?

**Comment by LTLA** [comment]
I took a pause for a bit. But you may be interested in its [open-source descendent](https://github.com/ArtifactDB); I have been daydreaming about creating a Julia client for it, possibly using **GenomicVectors.jl** as part of the stack.

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register
